name: QA DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: authenticate npm
      run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.PACKAGING_TOKEN }}

    - run: git config --global user.name ${{ secrets.RELEASE_USERNAME }}
    - run: git config --global user.email ${{ secrets.RELEASE_EMAIL }}

    - name: installing npm
      run: npm install

    - name: release
      run: npm run release